In [12]:
import pandas as pd
from nltk import tokenize
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\daniszab\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [13]:
df = pd.read_json('./resources/preprocessed.json')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52517 entries, 0 to 80602
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          52517 non-null  object
 1   date          52517 non-null  datetime64[ns]
 2   rating        52517 non-null  int64
 3   review        52517 non-null  object
 4   thumbs up     52517 non-null  int64
 5   total thumbs  52517 non-null  int64
 6   thumbs down   52517 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 3.2+ MB

In [30]:
review_index = 0
df_splitted = pd.DataFrame(columns=['review index', 'name', 'date', 'rating', 'review', 'thumbs up', 'total thumbs', 'thumbs down'])

In [32]:
for index, row in df.iterrows():
    sentences = tokenize.sent_tokenize(row['review'])
    for sentence in sentences:
        df_splitted.loc[df_splitted.shape[0]] = [review_index, row['name'], row['date'], row['rating'], sentence, row['thumbs up'], row['total thumbs'], row['thumbs down']]
    review_index = review_index + 1    

df_splitted

,review index,name,date,rating,review,thumbs up,total thumbs,thumbs down
0,0,SC4RECR00W,2020-06-19,1,believe got rid main character first game less...,320,427,107
1,1,Bucketanarchy,2020-06-20,0,say like would insulting game like .,237,365,128
2,1,Bucketanarchy,2020-06-20,0,game got pretentious garbage ever seen .,237,365,128
3,1,Bucketanarchy,2020-06-20,0,"naughty dog way hard "" subvert "" instead compl...",237,365,128
4,1,Bucketanarchy,2020-06-20,0,part 1 perfect balance story character develop...,237,365,128
...,...,...,...,...,...,...,...,...
263685,52515,J1mT,2021-11-17,10,"game immense , really hard handle times .",0,0,0
263686,52516,3b3al,2021-11-17,2,"game story poor , huge amount suck , make sen...",0,0,0
263687,52516,3b3al,2021-11-17,2,bad game .,0,0,0
263688,52516,3b3al,2021-11-17,2,"thing enjoyable game stealth action , rather a...",0,0,0
263689,52516,3b3al,2021-11-17,2,account specifically give rating .,0,0,0

In [34]:
df_splitted.to_json('./resources/splitted.json')